// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteGameByIdData, DeleteGameByIdErrors, DeleteGameByIdResponses, GetGameByIdData, GetGameByIdErrors, GetGameByIdResponses, PatchGameByIdData, PatchGameByIdErrors, PatchGameByIdResponses, PatchUserData, PatchUserErrors, PatchUserResponses, PostGameData, PostGameErrors, PostGameResponses, PostUserData, PostUserErrors, PostUserResponses, PutGameByIdData, PutGameByIdErrors, PutGameByIdResponses, PutUserData, PutUserErrors, PutUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Update user info
 *
 * name, and street address can be updated
 */
export const patchUser = <ThrowOnError extends boolean = false>(options: Options<PatchUserData, ThrowOnError>) => (options.client ?? client).patch<PatchUserResponses, PatchUserErrors, ThrowOnError>({
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Registers a new user
 *
 * Inserts a new user into the database
 */
export const postUser = <ThrowOnError extends boolean = false>(options: Options<PostUserData, ThrowOnError>) => (options.client ?? client).post<PostUserResponses, PostUserErrors, ThrowOnError>({
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login as a user
 *
 * Logs the user in with the email and password and it gives a new token
 */
export const putUser = <ThrowOnError extends boolean = false>(options: Options<PutUserData, ThrowOnError>) => (options.client ?? client).put<PutUserResponses, PutUserErrors, ThrowOnError>({
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add a new game to exchange
 *
 * Adds a new retro game to the exchange collection
 */
export const postGame = <ThrowOnError extends boolean = false>(options: Options<PostGameData, ThrowOnError>) => (options.client ?? client).post<PostGameResponses, PostGameErrors, ThrowOnError>({
    url: '/game',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a game
 *
 * Delete a game with the provided ID
 */
export const deleteGameById = <ThrowOnError extends boolean = false>(options: Options<DeleteGameByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteGameByIdResponses, DeleteGameByIdErrors, ThrowOnError>({ url: '/game/{id}', ...options });

/**
 * Get game info
 *
 * Get info from a game with the specified ID
 */
export const getGameById = <ThrowOnError extends boolean = false>(options: Options<GetGameByIdData, ThrowOnError>) => (options.client ?? client).get<GetGameByIdResponses, GetGameByIdErrors, ThrowOnError>({ url: '/game/{id}', ...options });

/**
 * Update some attributes of a game
 *
 * Updates the provided fields of a game
 */
export const patchGameById = <ThrowOnError extends boolean = false>(options: Options<PatchGameByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchGameByIdResponses, PatchGameByIdErrors, ThrowOnError>({
    url: '/game/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Replace all properties of a game
 *
 * Updates the entire game provided by the ID
 */
export const putGameById = <ThrowOnError extends boolean = false>(options: Options<PutGameByIdData, ThrowOnError>) => (options.client ?? client).put<PutGameByIdResponses, PutGameByIdErrors, ThrowOnError>({
    url: '/game/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
