// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

/**
 * A user object
 */
export type User = {
    /**
     * The name of the user
     */
    name: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The password of the user
     */
    password: string;
    /**
     * The street address of the user
     */
    streetAddress: string;
};

/**
 * A user object that has all optional fields
 */
export type UserPartial = {
    /**
     * The name of the user
     */
    name?: string;
    /**
     * The email of the user
     */
    email?: string;
    /**
     * The password of the user
     */
    password?: string;
    /**
     * The street address of the user
     */
    streetAddress?: string;
};

/**
 * Parts of a user object that are required for login
 */
export type LoginUser = {
    /**
     * The email of the user
     */
    email: string;
    /**
     * The password of the user
     */
    password: string;
};

/**
 * An object that contains a bearer token
 */
export type UserToken = {
    /**
     * The bearer token for the user
     */
    token: string;
};

/**
 * A game object
 */
export type Game = {
    /**
     * Name of the game
     */
    name: string;
    /**
     * Who the game was published by
     */
    publisher: string;
    /**
     * The year the game was released
     */
    year: number;
    /**
     * The platforms that this game is available on
     */
    platforms: Array<string>;
    /**
     * The condition the physical game cartridge is in (mint, good, fair, poor)
     */
    condition: string;
    /**
     * The number of previous owners of this game
     */
    previousOwners?: number;
};

/**
 * A game object that has all optional fields
 */
export type GamePartial = {
    /**
     * Name of the game
     */
    name?: string;
    /**
     * Who the game was published by
     */
    publisher?: string;
    /**
     * The year the game was released
     */
    year?: number;
    /**
     * The platforms that this game is available on
     */
    platforms?: Array<string>;
    /**
     * The condition the physical game cartridge is in
     */
    condition?: string;
    /**
     * The number of previous owners of this game
     */
    previousOwners?: number;
};

/**
 * An object for exchanging a game to a specific user
 */
export type GameExchange = {
    /**
     * The ID of the user that is sending the game up for exchange
     */
    fromUserID?: number;
    /**
     * The email of the user to exchange the game to
     */
    toUserEmail: string;
    /**
     * The ID of the game that is being requested in exchange
     */
    requestedGameID?: number;
};

/**
 * An error that can occur due to empty bodies or invalid fields
 */
export type InvalidFieldError = {
    message: string;
    /**
     * The field that caused the error
     */
    field: string;
    /**
     * The invalid value provided
     */
    value: string;
};

/**
 * An error that occurs from invalid access or invalid login
 */
export type UnauthorizedError = {
    message: string;
};

/**
 * An error that occurs when authorization is valid but the action is not allowed
 */
export type ForbiddenError = {
    message: string;
};

/**
 * An error that occurs when a requested resource is not found
 */
export type NotFoundError = {
    message: string;
    /**
     * The ID that was not found
     */
    triedID: number;
};

/**
 * An error that occurs when a collision happens with resources
 */
export type AlreadyExistsError = {
    message: string;
};

/**
 * An error that occurs from an internal server issue
 */
export type InternalServerError = {
    message: string;
};

/**
 * The ID of a game
 */
export type GameId = number;

/**
 * The ID of a user
 */
export type UserId = number;

/**
 * Bearer token for user authentication
 */
export type AuthToken = string;

export type GetUserData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Missing bearer token or token is invalid
     */
    401: UnauthorizedError;
    /**
     * User not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserPartial;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PatchUserData = {
    body: UserPartial;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a user
         */
        ID: number;
    };
    query?: never;
    url: '/user';
};

export type PatchUserErrors = {
    /**
     * Problem parsing body or invalid user field
     */
    400: InvalidFieldError;
    /**
     * Missing bearer token or token is invalid
     */
    401: UnauthorizedError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PatchUserError = PatchUserErrors[keyof PatchUserErrors];

export type PatchUserResponses = {
    /**
     * User details updated
     */
    200: {
        message: string;
    };
    /**
     * Body is empty
     */
    204: {
        message: string;
    };
};

export type PatchUserResponse = PatchUserResponses[keyof PatchUserResponses];

export type PostUserData = {
    body: User;
    path?: never;
    query?: never;
    url: '/user';
};

export type PostUserErrors = {
    /**
     * Invalid user field or missing body
     */
    400: InvalidFieldError;
    /**
     * User with that email already exists
     */
    409: AlreadyExistsError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PostUserError = PostUserErrors[keyof PostUserErrors];

export type PostUserResponses = {
    /**
     * User Created
     */
    201: UserToken;
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];

export type PutUserData = {
    body: LoginUser;
    path?: never;
    query?: never;
    url: '/user';
};

export type PutUserErrors = {
    /**
     * Invalid user field or missing body
     */
    400: InvalidFieldError;
    /**
     * Invalid email or password
     */
    401: UnauthorizedError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PutUserError = PutUserErrors[keyof PutUserErrors];

export type PutUserResponses = {
    /**
     * Logged in successfully
     */
    200: UserToken;
};

export type PutUserResponse = PutUserResponses[keyof PutUserResponses];

export type PostGameData = {
    body: Game;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/game';
};

export type PostGameErrors = {
    /**
     * Invalid game field or missing body
     */
    400: InvalidFieldError;
    /**
     * The user is not authorized or is missing a token
     */
    401: UnauthorizedError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PostGameError = PostGameErrors[keyof PostGameErrors];

export type PostGameResponses = {
    /**
     * Game Created
     */
    201: Game;
};

export type PostGameResponse = PostGameResponses[keyof PostGameResponses];

export type DeleteGameByIdData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/game/{id}';
};

export type DeleteGameByIdErrors = {
    /**
     * User is not authorized to delete this game or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type DeleteGameByIdError = DeleteGameByIdErrors[keyof DeleteGameByIdErrors];

export type DeleteGameByIdResponses = {
    /**
     * Deleted Game
     */
    200: Game;
};

export type DeleteGameByIdResponse = DeleteGameByIdResponses[keyof DeleteGameByIdResponses];

export type GetGameByIdData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/game/{id}';
};

export type GetGameByIdErrors = {
    /**
     * The user is not authorized to view games
     */
    401: UnauthorizedError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type GetGameByIdError = GetGameByIdErrors[keyof GetGameByIdErrors];

export type GetGameByIdResponses = {
    /**
     * OK
     */
    200: Game;
};

export type GetGameByIdResponse = GetGameByIdResponses[keyof GetGameByIdResponses];

export type PatchGameByIdData = {
    body: GamePartial;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/game/{id}';
};

export type PatchGameByIdErrors = {
    /**
     * Invalid game field or missing body
     */
    400: InvalidFieldError;
    /**
     * User is not authorized to update this game or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PatchGameByIdError = PatchGameByIdErrors[keyof PatchGameByIdErrors];

export type PatchGameByIdResponses = {
    /**
     * Updated game
     */
    200: Game;
    /**
     * Body is empty
     */
    204: Game;
};

export type PatchGameByIdResponse = PatchGameByIdResponses[keyof PatchGameByIdResponses];

export type PutGameByIdData = {
    body: Game;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/game/{id}';
};

export type PutGameByIdErrors = {
    /**
     * Invalid game field or missing body
     */
    400: InvalidFieldError;
    /**
     * User is not authorized to update this game or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PutGameByIdError = PutGameByIdErrors[keyof PutGameByIdErrors];

export type PutGameByIdResponses = {
    /**
     * Updated game
     */
    200: Game;
};

export type PutGameByIdResponse = PutGameByIdResponses[keyof PutGameByIdResponses];

export type DeleteExchangeByIdData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/exchange/{id}';
};

export type DeleteExchangeByIdErrors = {
    /**
     * User is not authorized to cancel this exchange or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type DeleteExchangeByIdError = DeleteExchangeByIdErrors[keyof DeleteExchangeByIdErrors];

export type DeleteExchangeByIdResponses = {
    /**
     * Exchange cancelled
     */
    200: Game;
};

export type DeleteExchangeByIdResponse = DeleteExchangeByIdResponses[keyof DeleteExchangeByIdResponses];

export type GetExchangeByIdData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/exchange/{id}';
};

export type GetExchangeByIdErrors = {
    /**
     * User has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type GetExchangeByIdError = GetExchangeByIdErrors[keyof GetExchangeByIdErrors];

export type GetExchangeByIdResponses = {
    /**
     * OK
     */
    200: GameExchange;
};

export type GetExchangeByIdResponse = GetExchangeByIdResponses[keyof GetExchangeByIdResponses];

export type PostExchangeByIdData = {
    body: GameExchange;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/exchange/{id}';
};

export type PostExchangeByIdErrors = {
    /**
     * Invalid exchange field or missing body
     */
    400: InvalidFieldError;
    /**
     * User is not authorized to exchange this game or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * The receiver must own the requested game to exchange
     */
    403: ForbiddenError;
    /**
     * Game not found
     */
    404: NotFoundError;
    /**
     * Game is already up for exchange
     */
    409: AlreadyExistsError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PostExchangeByIdError = PostExchangeByIdErrors[keyof PostExchangeByIdErrors];

export type PostExchangeByIdResponses = {
    /**
     * Game is up for exchange
     */
    201: GameExchange;
};

export type PostExchangeByIdResponse = PostExchangeByIdResponses[keyof PostExchangeByIdResponses];

export type PostExchangeByIdAcceptData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/exchange/{id}/accept';
};

export type PostExchangeByIdAcceptErrors = {
    /**
     * User is not authorized to receive this game or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game exchange not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PostExchangeByIdAcceptError = PostExchangeByIdAcceptErrors[keyof PostExchangeByIdAcceptErrors];

export type PostExchangeByIdAcceptResponses = {
    /**
     * Received Game
     */
    200: Game;
};

export type PostExchangeByIdAcceptResponse = PostExchangeByIdAcceptResponses[keyof PostExchangeByIdAcceptResponses];

export type PostExchangeByIdDeclineData = {
    body?: never;
    headers: {
        /**
         * Bearer token for user authentication
         */
        Authorization: string;
    };
    path: {
        /**
         * The ID of a game
         */
        ID: number;
    };
    query?: never;
    url: '/exchange/{id}/decline';
};

export type PostExchangeByIdDeclineErrors = {
    /**
     * User is not authorized to cancel this exchange or has a missing or invalid token
     */
    401: UnauthorizedError;
    /**
     * Game exchange not found
     */
    404: NotFoundError;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type PostExchangeByIdDeclineError = PostExchangeByIdDeclineErrors[keyof PostExchangeByIdDeclineErrors];

export type PostExchangeByIdDeclineResponses = {
    /**
     * Cancelled Exchange
     */
    200: Game;
};

export type PostExchangeByIdDeclineResponse = PostExchangeByIdDeclineResponses[keyof PostExchangeByIdDeclineResponses];
